name: sweetscoop-front

services:
  frontend:
    container_name: sweetscoop-frontend

    image: ${FRONT_IMAGE:-sweetscoop-frontend:latest}

    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "80:80"

    networks:
      - sweetscoop-network

networks:
  sweetscoop-network:
    external: true