name: sweetscoop

services:
  backend:
    container_name: sweetscoop-backend

    build:
      context: ../../Spring_Boot_workspace/SweetScoopBack
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      SERVER_PORT: 8888

      # 기존 Docker MySQL이 Windows의 3307 포트로 실행 중일 때
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/sweetscoop?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234

      TOSS_SECRET_KEY: ${TOSS_SECRET_KEY}
      TZ: Asia/Seoul
      PRINTER_URL: http://host.docker.internal:8888/receipt

    ports:
      - "8889:8888"

    networks:
      - sweetscoop-network


  frontend:
    container_name: sweetscoop-frontend

    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - sweetscoop-network


networks:
  sweetscoop-network:
    driver: bridge